### ISSUE TITLE
You can't ever get an F with this app

### ISSUE THREAD

**Issue by flyrev** [TravisHoover/Scala-Grading-app#1]
Shouldn't
   else if (totalPoints > 60)
be   
   else if (totalPoints < 60 && totalPoints >= 0)
?

):

**Comment by TravisHoover** [comment]
It absolutely should! Good catch, I guess I never ran it against a test case that resulted in an F grade.

**Comment by TravisHoover** [comment]
Resolved with pull request https://github.com/TravisHoover/Scala-Grading-app/pull/2. Thanks!
